export const ALUTENT_COLUMNS = [
  'product_id_SM',
  'product_id',
  'supplierNo',
  'brand',
  'name_de',
  'name_en',
  'name_hu',
  'ean',
  'length',
  'width',
  'height',
  'weight',
  'Color_de',
  'Color_en',
  'Color_hu',
  'packageweight',
  'packagevolume',
  'long_description_de',
  'long_description_en',
  'long_description_hu',
  'recommendet_retail_price_with_german_tax',
  'recommendet_retail_price_with_tax_HUF',
  'streetprice_with_german_tax',
  'streetprice_without_HUN_tax_HUF',
  'merchant_price',
  'merchant_price_HUF',
  'youtubevideo',
  'bild1',
  'bild2',
  'bild3',
  'bild4',
  'bild5',
  'freightlevel',
  'stocklevel',
  'availability_in_weeks',
  'youtubeid',
  'categoriy2_id',
  'cat1Name',
  'cat2Name',
  'Cat3Name',
  'inCategories',
  'crm_category_slug',
  'crm_supplier_slug',
  'crm_warehouse_slug',
  'is_consumable',
  'discontinued',
  'cat1Name_en',
  'cat2Name_en',
  'cat3Name_en',
  'cat1Name_hu',
  'cat2Name_hu',
  'cat3Name_hu',
  'Relatedproduct_1',
  'Relatedproduct_pc_1',
  'Relatedproduct_2',
  'Relatedproduct_pc_2',
  'Relatedproduct_3',
  'Relatedproduct_pc_3',
  'Relatedproduct_4',
  'Relatedproduct_pc_4',
  'Owner',
  'warehouse 1.',
  'warehouse 2.',
  'warehouse 3.',
  'RentFeeDay',
  'RentFeeWeekend',
  'RentFeeWeek',
  'Discont 1.',
  'Discont 2.',
  'Rent',
] as const;

export type AlutentColumn = (typeof ALUTENT_COLUMNS)[number];
